[package]
name = "memorix"
version = "2.0.0-rc3"
edition = "2021"

[dependencies]
nom = "7.1.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
stringcase = "0.3.0"

[dev-dependencies]
insta = "1.40.0"
