name: Cli

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./cli/yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Format
        run: yarn format:check
      - name: Lint
        run: yarn lint:err
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test
