name: Client Redis Rust

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: 1.81.0
      - name: Install
        run: make install
      - name: Format
        run: make format-check
      - name: Lint
        run: make lint
      - name: Typecheck
        run: make typecheck
      - name: Test
        run: make test
