name: Release

on:
  push:
    branches:
      - master
      - next
      - 8-add-code-to-client-js-so-the-generated-code-will-work-with-it

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients/redis/js
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./clients/redis/js/yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
