name: Release

on:
  push:
    branches:
      - master
      - release
      - next

jobs:
  build-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./cli/yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu_latest
          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}/cli:/cli"
          install: |
            export NVM_DIR=$HOME/.nvm
            export NODE_VERSION=16.14.2
            export NODE_PATH=$NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
            export PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
            . $NVM_DIR/nvm.sh
            nvm install $NODE_VERSION
            nvm alias default $NODE_VERSION
            nvm use default
            npm install --global yarn
          run: |
            export NVM_DIR=$HOME/.nvm
            export NODE_VERSION=16.14.2
            export NODE_PATH=$NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
            export PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
            cd /cli
            yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-cli
          path: ./cli/lib/release
          retention-days: 1
  build-client-redis-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients/redis/js
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./clients/redis/js/yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-client-redis-js
          path: ./clients/redis/js/lib
          retention-days: 1
  release:
    needs: [build-cli, build-client-redis-js]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
          cache: "poetry"
          cache-dependency-path: ./clients/redis/python/poetry.lock
      - name: Install dependencies
        run: yarn install
      - uses: actions/download-artifact@v3
      - name: Move artifacts to projects
        run: |
          mkdir ./cli/lib && mkdir ./cli/lib/release && mv -v artifact-cli/* ./cli/lib/release
          mkdir ./clients/redis/js/lib && mv -v artifact-client-redis-js/* ./clients/redis/js/lib
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: (cd ./clients/redis/python && npx semantic-release)
