name: Release

on:
  push:
    branches:
      - 55-rust-support
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: |
            ./yarn.lock
            ./cli/yarn.lock
            ./clients/redis/js/yarn.lock
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
          cache: "poetry"
          cache-dependency-path: ./clients/redis/python/poetry.lock
      - name: Install dependencies
        run: yarn install
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
      - name: Create empty docs build dir
        run: mkdir ./docs/public
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: npx semantic-release
